BMLT WordPress Satellite: BMLTWPPlugin Class Reference
BMLTWPPlugin Class Reference
This is the class that implements and encapsulates the plugin functionality. * A single instance of this is created, and manages the plugin. *
This plugin registers errors by echoing HTML comments, so look at the source code of * the page if things aren't working right. *.
Public Member Functions
__construct ()
Constructor. *.
enqueueFrontendFilesBmlt ()
stop_filter_if_not_main ()
Sets the flag if this is a singular post or page. Otherwise, we don't show. *.
admin_page ()
Presents the admin page. *.
option_menu ()
Presents the admin menu options. *
NOTE: This function requires WP. Most of the rest can probably be more easily * converted for other CMSes. *.
content_filter ($in_the_content)
Massages the page content. * *.
filter_plugin_actions ($links, $file)
This was cribbed from the W3TC (TotalCache) plugin. *
This function adds a settings link to the plugin listing. *.
filter_init ()
This is called before anything else. *.
standard_head ($from_admin=false)
Echoes any necessary head content. *.
admin_head ()
Echoes any necessary head content for the admin. *.
Public Attributes
$plugin_read_me_loc = 'http://plugins.trac.wordpress.org/browser/bmlt-wordpress-satellite-plugin/trunk/readme.txt?format=txt'
$plugin_file_name = 'bmlt-wordpress-satellite-plugin/bmlt-wordpress-satellite-plugin.php'
$plugin_update_message_1 = 'The WordPress BMLT Plugin has been updated. Here is a change list, so you can see what\'s been changed or fixed:'
$plugin_update_message_2 = '= Latest Version ='
$plugin_update_message_3 = 'Release Date:'
$plugin_settings_name = 'Settings'
$plugin_is_main = true
Protected Member Functions
get_admin_ajax_base_uri ()
Return an HTTP path to the AJAX callback target. * *.
get_admin_form_uri ()
Return an HTTP path to the basic admin form submit (action) URI * *.
cms_get_post_meta ($in_page_id, $in_settings_id)
This gets the page meta for the given page. (allows CMS abstraction). * *.
cms_get_page_settings_id ($in_content, $in_check_mobile=false)
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
cms_get_option ($in_option_key)
This gets the admin options from the database (allows CMS abstraction). * *.
cms_set_option ($in_option_key, $in_option_value)
This gets the admin options from the database (allows CMS abstraction). *.
cms_delete_option ($in_option_key)
Deletes a stored option (allows CMS abstraction). *.
get_plugin_path ()
Return an HTTP path to the plugin directory. * *.
set_callbacks ()
Sets up the admin and handler callbacks. *.
process_text ($in_string)
This uses the WordPress text processor (__) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
Detailed Description
This is the class that implements and encapsulates the plugin functionality. * A single instance of this is created, and manages the plugin. *
This plugin registers errors by echoing HTML comments, so look at the source code of * the page if things aren't working right. *.
Definition at line 56 of file bmlt-wordpress-satellite-plugin.php.
Constructor & Destructor Documentation
__construct()
BMLTWPPlugin::__construct ()
Constructor. *.
Definition at line 70 of file bmlt-wordpress-satellite-plugin.php.
     {
         add_action( 'wp_enqueue_scripts', 'enqueueFrontendFilesBmlt' );
         parent::__construct();
     }
Member Function Documentation
admin_head()
BMLTWPPlugin::admin_head ()
Echoes any necessary head content for the admin. *.
Definition at line 457 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $head_content = $this->standard_head(true)."\n";   // We start with the standard stuff.
         $head_content .= "<!-- Also Added by the BMLT plugin 3.X. -->\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\n<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\n";
         $options = $this->getBMLTOptions(1);    // All options contain the admin key.
         $key = $options['google_api_key'];
         // Include the Google Maps API V3 files.
         $head_content .= '<script type="text/javascript" src="https://maps.google.com/maps/api/js?key='.$key.'"></script>';  // Load the Google Maps stuff for our map.
         if (function_exists('plugins_url')) {
             $head_content .= '<link rel="stylesheet" type="text/css" href="';
             $url = $this->get_plugin_path();
             $head_content .= htmlspecialchars($url);
             $head_content .= 'admin_styles.css" />';
             $head_content .= '<script type="text/javascript" src="';
             $head_content .= htmlspecialchars($url);
             $head_content .= 'admin_javascript.js"></script>';
         } else {
             echo "<!-- BMLTPlugin ERROR (head)! No plugins_url()! -->";
         }
         $head_content .= "\n<!-- End Also Added by the BMLT plugin 3.X. -->\n";
         echo $head_content;
     }
References get_plugin_path(), and standard_head().
admin_page()
BMLTWPPlugin::admin_page ()
Presents the admin page. *.
Definition at line 200 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         echo $this->return_admin_page();
     }
cms_delete_option()
BMLTWPPlugin::cms_delete_option ($in_option_key) protected
Deletes a stored option (allows CMS abstraction). *.
Parameters
$in_option_key The name of the option
Definition at line 532 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if (function_exists('delete_option')) {
             $ret = delete_option($in_option_key);
         } else {
             echo "<!-- BMLTPlugin ERROR (cms_delete_option)! No delete_option()! -->";
         }
     }
cms_get_option()
BMLTWPPlugin::cms_get_option ($in_option_key) protected
This gets the admin options from the database (allows CMS abstraction). * *.
Returns
an associative array, with the option settings. *
Parameters
$in_option_key The name of the option
Definition at line 497 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = $this->geDefaultBMLTOptions();
         if (function_exists('get_option')) {
             $ret = get_option($in_option_key);
         } else {
             echo "<!-- BMLTPlugin ERROR (cms_get_option)! No get_option()! -->";
         }
         return $ret;
     }
cms_get_page_settings_id()
BMLTWPPlugin::cms_get_page_settings_id ($in_content, $in_check_mobile = false) protected
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
Returns
a mixed type, with the settings ID. *
Parameters
$in_content Required (for the base version) content to check.
$in_check_mobile True if this includes a check for mobile. Default is false.
Definition at line 136 of file bmlt-wordpress-satellite-plugin.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $my_option_id = null;
         $page_id = null;
         $page = get_page($page_id);
         if (!$in_check_mobile && isset($this->my_http_vars['bmlt_settings_id']) && is_array($this->getBMLTOptions($this->my_http_vars['bmlt_settings_id']))) {
             $my_option_id = $this->my_http_vars['bmlt_settings_id'];
         } else {
             $cms_post_meta_mobile = isset($page->ID) && !empty($page->ID) ? $this->cms_get_post_meta($page->ID, 'bmlt_mobile') : '';
             $support_mobile = preg_replace('/\D/', '', trim($cms_post_meta_mobile));
             if (!$support_mobile && $in_check_mobile) {
                 $support_mobile = self::get_shortcode($in_content, 'bmlt_mobile');
                 if ($support_mobile === true) {
                     $options = $this->getBMLTOptions(1);
                     $support_mobile = strval($options['id']);
                 }
             }
             if ($in_check_mobile && $support_mobile && !isset($this->my_http_vars['BMLTPlugin_mobile']) && (self::mobile_sniff_ua($this->my_http_vars) != 'xhtml')) {
                 $my_option_id = $support_mobile;
             } elseif (!$in_check_mobile) {
                 $cms_post_meta_settings = isset($page->ID) && !empty($page->ID) ? $this->cms_get_post_meta($page->ID, 'bmlt_settings_id') : '';
                 $my_option_id = intval(preg_replace('/\D/', '', trim($cms_post_meta_settings)));
                 if (isset($this->my_http_vars['bmlt_settings_id']) && intval($this->my_http_vars['bmlt_settings_id'])) {
                     $my_option_id = intval($this->my_http_vars['bmlt_settings_id']);
                 } elseif ($in_content = isset($in_content) ? $in_content : (isset($page->post_content) ? $page->post_content : null)) {
                     $my_option_id_content = parent::cms_get_page_settings_id($in_content, $in_check_mobile);
                     $my_option_id = $my_option_id_content ?: $my_option_id;
                 }
                 if (!$my_option_id) {   // If nothing else gives, we go for the default (first) settings.
                     $options = $this->getBMLTOptions(1);
                     $my_option_id = $options['id'];
                 }
             }
         }
         return $my_option_id;
     }
References cms_get_post_meta().
Referenced by standard_head().
cms_get_post_meta()
BMLTWPPlugin::cms_get_post_meta ($in_page_id, $in_settings_id) protected
This gets the page meta for the given page. (allows CMS abstraction). * *.
Returns
a mixed type, with the meta data *
Parameters
$in_page_id The ID of the page/post
$in_settings_id The ID of the meta tag to fetch
Definition at line 111 of file bmlt-wordpress-satellite-plugin.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         if (function_exists('get_post_meta')) {
             $ret = get_post_meta($in_page_id, $in_settings_id, true);
         } else {
             echo "<!-- BMLTPlugin ERROR (cms_get_post_meta)! No get_post_meta()! -->";
         }
         return $ret;
     }
Referenced by cms_get_page_settings_id(), and content_filter().
cms_set_option()
BMLTWPPlugin::cms_set_option ($in_option_key, $in_option_value) protected
This gets the admin options from the database (allows CMS abstraction). *.
Parameters
$in_option_key The name of the option
$in_option_value the values to be set (associative array)
Definition at line 515 of file bmlt-wordpress-satellite-plugin.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         // Added a test, to prevent the creation of multiple empty settings by low-rank users trying SQL injections.
         if (function_exists('update_option') && is_array($in_option_value) && count($in_option_value)) {
             $ret = update_option($in_option_key, $in_option_value);
         } elseif (is_array($in_option_value) && count($in_option_value)) {
             echo "<!-- BMLTPlugin ERROR (cms_set_option)! No update_option()! -->";
         }
     }
content_filter()
BMLTWPPlugin::content_filter ($in_the_content)
Massages the page content. * *.
Returns
a string, containing the "massaged" content. *
Parameters
$in_the_content The content in need of filtering.
Definition at line 237 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if ($this->plugin_is_main) {
             // Simple searches can be mixed in with other content.
             $in_the_content = parent::content_filter($in_the_content);
             $count = 0;
             $in_the_content = $this->display_popup_search($in_the_content, $this->cms_get_post_meta(get_the_ID(), 'bmlt_simple_searches'), $count);
         } else // If we are not in a page in the main display, we remove the shortcodes.
             {
             $in_the_content = self::replace_shortcode($in_the_content, 'bmlt', '');
             $in_the_content = self::replace_shortcode($in_the_content, 'bmlt_map', '');
             $in_the_content = self::replace_shortcode($in_the_content, 'simple_search_list', '');
             $in_the_content = self::replace_shortcode($in_the_content, 'bmlt_mobile', '');
             $in_the_content = self::replace_shortcode($in_the_content, 'bmlt_simple', '');
             $in_the_content = self::replace_shortcode($in_the_content, 'bmlt_changes', '');
             $in_the_content = self::replace_shortcode($in_the_content, 'bmlt_quicksearch', '');
             $in_the_content = self::replace_shortcode($in_the_content, 'bmlt_table', '');
         }
         return $in_the_content;
     }
References cms_get_post_meta().
filter_init()
BMLTWPPlugin::filter_init ()
This is called before anything else. *.
Definition at line 288 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         ob_start(); // This prevents themes and plugins from screwing us over.
         $this->ajax_router();
     }
filter_plugin_actions()
BMLTWPPlugin::filter_plugin_actions ($links, $file)
This was cribbed from the W3TC (TotalCache) plugin. *
This function adds a settings link to the plugin listing. *.
Definition at line 267 of file bmlt-wordpress-satellite-plugin.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         static $this_plugin;
         if (!$this_plugin && function_exists('plugin_basename')) {
             if ($file == plugin_basename(__FILE__)) {
                 $settings_link = '<a href="options-general.php?page=' . basename(__FILE__) . '">' . $this->process_text($this->plugin_settings_name) . '</a>';
                 array_unshift($links, $settings_link);
             }
         }
         return $links;
     }
References process_text().
get_admin_ajax_base_uri()
BMLTWPPlugin::get_admin_ajax_base_uri () protected
Return an HTTP path to the AJAX callback target. * *.
Returns
a string, containing the path. *
Definition at line 87 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->get_admin_form_uri();
     }
References get_admin_form_uri().
get_admin_form_uri()
BMLTWPPlugin::get_admin_form_uri () protected
Return an HTTP path to the basic admin form submit (action) URI * *.
Returns
a string, containing the path. *
Definition at line 99 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $_SERVER['PHP_SELF'].'?page=bmlt-wordpress-satellite-plugin.php';
     }
Referenced by get_admin_ajax_base_uri().
get_plugin_path()
BMLTWPPlugin::get_plugin_path () protected
Return an HTTP path to the plugin directory. * *.
Returns
a string, containing the path. *
Definition at line 548 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $url = '';
         if (function_exists('plugins_url')) {
             if (plugins_url()) {
                 $url = plugins_url()."/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/";
             } elseif (defined('WP_PLUGIN_URL')) {
                 $url = WP_PLUGIN_URL."/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/";
             } else {
                 echo "<!-- BMLTPlugin ERROR (get_plugin_path)! Empty plugins_url() and no WP_PLUGIN_URL! -->";
             }
         } elseif (!function_exists('plugins_url') && defined('WP_PLUGIN_URL')) {
             $url = WP_PLUGIN_URL."/bmlt-wordpress-satellite-plugin/vendor/bmlt/bmlt-satellite-base-class/";
         } else {
             echo "<!-- BMLTPlugin ERROR (get_plugin_path)! No plugins_url() and no WP_PLUGIN_URL! -->";
         }
         return $url;
     }
Referenced by admin_head(), and standard_head().
option_menu()
BMLTWPPlugin::option_menu ()
Presents the admin menu options. *
NOTE: This function requires WP. Most of the rest can probably be more easily * converted for other CMSes. *.
Definition at line 213 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         global $bmlt_localization;
         $this->adapt_to_lang($bmlt_localization);
         if (function_exists('add_options_page') && (self::get_plugin_object() instanceof BMLTPlugin)) {
             $options_title = $this->my_current_language->local_options_title;
             $menu_string = $this->my_current_language->local_menu_string;
             add_options_page($options_title, $menu_string, 9, basename(__FILE__), array ( self::get_plugin_object(), 'admin_page' ));
         } elseif (!function_exists('add_options_page')) {
             echo "<!-- BMLTPlugin ERROR (option_menu)! No add_options_page()! -->";
         } else {
             echo "<!-- BMLTPlugin ERROR (option_menu)! No BMLTPlugin Object! -->";
         }
     }
process_text()
BMLTWPPlugin::process_text ($in_string) protected
This uses the WordPress text processor (__) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
Returns
a string, processed by WP. *
Parameters
$in_string The string to be processed.
Definition at line 605 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if (function_exists('__')) {
             $in_string = htmlspecialchars(__($in_string, 'BMLTPlugin'));
         } else {
             echo "<!-- BMLTPlugin Warning (process_text): __() does not exist! -->";
         }
         return $in_string;
     }
Referenced by filter_plugin_actions().
set_callbacks()
BMLTWPPlugin::set_callbacks () protected
Sets up the admin and handler callbacks. *.
Definition at line 573 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if (function_exists('add_filter')) {
             add_filter('the_content', array ( self::get_plugin_object(), 'content_filter'));
             add_filter('wp_head', array ( self::get_plugin_object(), 'standard_head' ));
             add_filter('admin_head', array ( self::get_plugin_object(), 'admin_head' ));
             add_filter('plugin_action_links', array ( self::get_plugin_object(), 'filter_plugin_actions' ), 10, 2);
         } else {
             echo "<!-- BMLTPlugin ERROR (set_callbacks)! No add_filter()! -->";
         }
         if (function_exists('add_action')) {
             add_action('pre_get_posts', array ( self::get_plugin_object(), 'stop_filter_if_not_main' ));
             add_action('admin_init', array ( self::get_plugin_object(), 'admin_ajax_handler' ));
             add_action('admin_menu', array ( self::get_plugin_object(), 'option_menu' ));
             add_action('init', array ( self::get_plugin_object(), 'filter_init' ));
         } else {
             echo "<!-- BMLTPlugin ERROR (set_callbacks)! No add_action()! -->";
         }
     }
standard_head()
BMLTWPPlugin::standard_head ($from_admin = false)
Echoes any necessary head content. *.
BASE CLASS OVERRIDES *
Parameters
$from_admin True, if this was called from the admin.
Definition at line 303 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $load_head = false;   // This is a throwback. It prevents the GM JS from being loaded if there is no directly specified settings ID.
         $head_content = "";
         $load_head = true;
         $additional_css = '';
         // If you specify the bmlt_mobile custom field in this page (not post), then it can force the browser to redirect to a mobile handler.
         // The value of bmlt_mobile must be the settings ID of the server you want to handle the mobile content.
         // Post redirectors are also handled, but at this point, only the page will be checked.
         $page_id = null;
         $page = get_page($page_id);
         $support_mobile = isset($page->post_content) && !empty($page->post_content) ? $this->cms_get_page_settings_id($page->post_content, true) : null;
         if ($support_mobile) {
             $mobile_options = $this->getBMLTOptions_by_id($support_mobile);
         } else {
             $support_mobile = null;
         }
         $options_standard = isset($page->post_content) && !empty($page->post_content) ? $page->post_content : null;
         $options = $this->getBMLTOptions_by_id($this->cms_get_page_settings_id($options_standard));
         if ($support_mobile && is_array($mobile_options) && count($mobile_options)) {
             $mobile_url = $_SERVER['PHP_SELF'].'?BMLTPlugin_mobile&bmlt_settings_id='.$support_mobile;
             if (isset($this->my_http_vars['WML'])) {
                 $mobile_url .= '&WML='.intval($this->my_http_vars['WML']);
             }
             if (isset($this->my_http_vars['simulate_smartphone'])) {
                 $mobile_url .= '&simulate_smartphone';
             }
             ob_end_clean();
             header("location: $mobile_url");
             die();
         }
         if ($from_admin
             ||  !$page
             ||  $support_mobile
             ||  $this->get_shortcode($page->post_content, 'bmlt')
             ||  $this->get_shortcode($page->post_content, 'bmlt_mobile')
             ||  $this->get_shortcode($page->post_content, 'bmlt_map')
             ||  $this->get_shortcode($page->post_content, 'bmlt_table')
             ||  $this->get_shortcode($page->post_content, 'bmlt_quicksearch')
             ||  $this->get_shortcode($page->post_content, 'bmlt_simple')
             ||  $this->get_shortcode($page->post_content, 'bmlt_changes')
             ||  $this->get_shortcode($page->post_content, 'simple_search_list')
             ) {
             $head_content = "<!-- Added by the BMLT plugin 3.X. -->\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\n<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\n";
             ## TODO: Is this right?
             if (isset($page->post_content) && !$this->get_shortcode($page->post_content, 'bmlt')) {
                 $load_head = false;
             }
             $this->my_http_vars['start_view'] = $options['bmlt_initial_view'];
             $this->load_params();
             $root_server_root = $options['root_server'];
             $head_content .= '<meta name="BMLT-Root-URI" content="'.htmlspecialchars($root_server_root).'" />';
             $head_content .= "\n".'<style type="text/css">'."\n";
             $temp = self::stripFile('styles.css', $options['theme']);
             if ($temp) {
                 $image_dir_path = $this->get_plugin_path() . '/themes/' . $options['theme'] . '/images/';
                 $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
                 $head_content .= "\t$temp\n";
             }
             $temp = self::stripFile('nouveau_map_styles.css', $options['theme']);
             if ($temp) {
                 $image_dir_path = $this->get_plugin_path() . '/themes/' . $options['theme'] . '/images/';
                 $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
                 $head_content .= "\t$temp\n";
             }
             $head_content .= self::stripFile('table_styles.css') . "\n";
             $head_content .= self::stripFile('quicksearch.css') . "\n";
             $dirname = dirname(__FILE__) . '/vendor/bmlt/bmlt-satellite-base-class/themes';
             $dir = new DirectoryIterator($dirname);
             foreach ($dir as $fileinfo) {
                 if (!$fileinfo->isDot()) {
                     $fName = $fileinfo->getFilename();
                     $temp = self::stripFile("table_styles.css", $fName);
                     if ($temp) {
                         $image_dir_path = $this->get_plugin_path() . '/themes/' . $fName . '/images/';
                         $temp = str_replace('##-IMAGEDIR-##', $image_dir_path, $temp);
                         $head_content .= "\t$temp\n";
                     }
                     $temp = self::stripFile("quicksearch.css", $fName);
                     if ($temp) {
                         $head_content .= "\t$temp\n";
                     }
                 }
             }
             $additional_css = '#content div.bmlt_table_display_div ul.bmlt_table_data_ul { width:100%; }';
             $additional_css .= ' #content div.bmlt_table_display_div ul.bmlt_table_header_weekday_list,#content div.bmlt_table_display_div ul.bmlt_table_header_weekday_list li,#content div.bmlt_table_display_div div.bmlt_table_div ul,#content div.bmlt_table_display_div div.bmlt_table_div ul li { list-style-type:none;list-style-position:outside; }';
             $additional_css .= ' #content div.bmlt_table_display_div div.bmlt_table_div ul.bmlt_table_data_ul,#content div.bmlt_table_display_div div.bmlt_table_div ul.bmlt_table_data_ul li.bmlt_table_data_ul_li { margin:0;padding:0; } ';
             $additional_css .= ' #content div.bmlt_table_display_div ul.bmlt_table_data_ul li.bmlt_table_data_ul_li ul { margin:0;padding:0; } ';
             $additional_css .= self::stripFile('responsiveness.css') . "\n";
             if ($root_server_root) {
                 $additional_css .= '.bmlt_container * {margin:0;padding:0;text-align:center }';
                 if ($options['additional_css']) {
                     $additional_css .= $options['additional_css'];
                 }
                 if ($additional_css) {
                     $head_content .= $additional_css;
                 }
             }
             $head_content .= "\n</style>\n";
             $head_content .= '<script type="text/javascript">';
             $head_content .= self::stripFile('javascript.js');
             if (isset($page->post_content) && !empty($page->post_content) && $this->get_shortcode($page->post_content, 'bmlt_quicksearch')) {
                 $head_content .= self::stripFile('quicksearch.js') . (defined('_DEBUG_MODE_') ? "\n" : '');
             }
             if (isset($page->post_content) && !empty($page->post_content) && $this->get_shortcode($page->post_content, 'bmlt_map')) {
                 $head_content .= self::stripFile('map_search.js');
             }
             if (isset($page->post_content) && !empty($page->post_content) && $this->get_shortcode($page->post_content, 'bmlt_mobile')) {
                 $head_content .= self::stripFile('fast_mobile_lookup.js');
             }
             $head_content .= '</script>';
             $head_content .= "\n<!-- End Added by the BMLT plugin 3.X. -->\n";
             if (!$from_admin) {
                 echo $head_content;
             } else {
                 return $head_content;
             }
         }
     }
References cms_get_page_settings_id(), and get_plugin_path().
Referenced by admin_head().
stop_filter_if_not_main()
BMLTWPPlugin::stop_filter_if_not_main ()
Sets the flag if this is a singular post or page. Otherwise, we don't show. *.
THE WORDPRESS CALLBACKS *
Definition at line 190 of file bmlt-wordpress-satellite-plugin.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->plugin_is_main = is_singular();
     }
The documentation for this class was generated from the following file:
/home/runner/work/bmlt-wordpress-satellite-plugin/bmlt-wordpress-satellite-plugin/bmlt-wordpress-satellite-plugin.php