name: 'latest'

on:
  push:
    branches: [ 'master' ]

jobs:
  deploy-wordpress-satellite-latest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      BUILD_DIR: build
      DIST_DIR_S3: dist/s3
      DIST_DIR_GITHUB: dist/github
      GITHUB_RELEASE_FILENAME: bmlt-wordpress-satellite-plugin.zip
      S3_KEY: bmlt-wordpress-satellite-plugin
    steps:
      - uses: actions/checkout@v2
        id: code-checkout

      - name: Validate composer.json and composer.lock
        id: composer-validate
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        id: install-dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest

      - name: Prepare zip file
        run: |
          export ZIP_FILENAME=bmlt-wordpress-satellite-plugin-build${GITHUB_RUN_NUMBER}-${GITHUB_SHA}.zip
          echo "ZIP_FILENAME=${ZIP_FILENAME}" >> $GITHUB_ENV
          zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.github*" -x "*assets*" -x "*vendor/squizlabs*" -x "*.gitattributes"
          mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
          mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
          mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions/gh-ci-s3-artifact
          role-session-name: gh-actions-wordpress-satellite
          aws-region: us-east-1

      - name: copy artifacts to s3
        run: |
          aws s3 cp ${DIST_DIR_S3}/${ZIP_FILENAME} s3://${{ secrets.S3_BUCKET }}/${S3_KEY}/${ZIP_FILENAME}

      - name: Publish Release to Latest WP
        id: publish_latest
        uses: bmlt-enabled/wordpress-releases-github-action@v1
        with:
          file: ${{ env.DIST_DIR_S3 }}/${{ env.ZIP_FILENAME }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          s3_key: ${{ env.S3_KEY }}

  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docs
        if: github.ref == 'refs/heads/master'
        run: |
          sudo apt-get install -y doxygen
          mkdir docs && cd doc
          doxygen Doxyfile

      - name: Deploy Docs
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
