name: 'pull-request'

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code 🛒
        uses: actions/checkout@v4
        id: code-checkout

      - name: Validate composer.json and composer.lock 🎼
        id: composer-validate
        run: composer validate

      - name: PHPCS checker 🧹
        id: php-codesniffer
        run: make lint